export const CATEGORIES = {
  Electronics: [
    'Smartphone',
    'Laptop',
    'Smartwatch',
    'Wireless Earbuds',
    'Noise Cancelling Headphones',
    'Bluetooth Speaker',
    'Tablet',
    'Gaming Mouse',
    'Mechanical Keyboard',
    '4K Monitor',
    'External Hard Drive',
    'Power Bank',
    'USB-C Hub',
    'Webcam',
  ],
  Footwear: [
    'Running Shoes',
    'Basketball Sneakers',
    'Leather Boots',
    'Suede Loafers',
    'Slip-on Sandals',
    'Casual Canvas Shoes',
    'Training Shoes',
    'Hiking Boots',
  ],
  Apparel: [
    'Slim Fit Jeans',
    'Crewneck T-Shirt',
    'Pullover Hoodie',
    'Waterproof Jacket',
    'Chino Pants',
    'Athletic Shorts',
    'Wool Sweater',
    'Bomber Jacket',
    'Socks Multi-pack',
  ],
  Accessories: [
    'Leather Wallet',
    'Travel Backpack',
    'Polarized Sunglasses',
    'Minimalist Watch',
    'Baseball Cap',
    'Wool Beanie',
    'Duffel Bag',
    'Phone Case',
    'Leather Belt',
  ],
  'Home & Kitchen': [
    'Air Purifier',
    'Espresso Machine',
    'Robot Vacuum',
    'Electric Kettle',
    'Personal Blender',
    'Toaster Oven',
    'Slow Cooker',
    'Non-stick Fry Pan',
    'Chef Knife Set',
  ],
};

export const TAGS = [
  'premium',
  'wireless',
  'portable',
  'durable',
  'lightweight',
  'waterproof',
  'smart',
  'ergonomic',
  'compact',
  'high-performance',
  'eco-friendly',
  'limited-edition',
  'best-seller',
  'outdoor',
  'travel-friendly',
  'office',
  'home',
  'fitness',
];
