import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma.service';
import {
  SearchOptions,
  SearchProvider,
  SearchResult,
} from '../search.interface';

interface RawFtsRow {
  id: string;
  name: string;
  description: string;
  brand: string;
  category: string;
  tags: string[];
  price: number;
  rating: number;
  stock: number;
  score: number;
  highlighted_name?: string;
  highlighted_desc?: string;
}

interface CountRow {
  count: number;
}

interface ExplainRow {
  'QUERY PLAN'?: string;
  [key: string]: unknown;
}

interface TokensRow {
  parsed_query?: string;
}

@Injectable()
export class FtsProvider implements SearchProvider {
  constructor(private readonly prisma: PrismaService) {}

  async search(query: string, options?: SearchOptions): Promise<SearchResult> {
    const limit = options?.limit || 10;
    const offset = options?.offset || 0;

    if (!query) {
      return {
        engine: 'fts',
        latencyMs: 0,
        totalHits: 0,
        items: [],
        queryInfo: { rawQuery: '' },
      };
    }

    const sqlQuery = `SELECT id, name, description, brand, category, tags, price, rating, stock, "createdAt",
       ts_rank(search_vector, websearch_to_tsquery('english', $1))::float as score,
       ts_headline('english', name, websearch_to_tsquery('english', $1), 'StartSel="<b class=""search-highlight"">", StopSel=</b>, HighlightAll=TRUE') as highlighted_name,
       ts_headline('english', description, websearch_to_tsquery('english', $1), 'StartSel="<b class=""search-highlight"">", StopSel=</b>, MaxWords=30, MinWords=15') as highlighted_desc
FROM products 
WHERE search_vector @@ websearch_to_tsquery('english', $1)
ORDER BY score DESC 
LIMIT $2 OFFSET $3`;

    const explainSql = `EXPLAIN SELECT id, name, description, brand, category, tags, price, rating, stock, "createdAt"
FROM products 
WHERE search_vector @@ websearch_to_tsquery('english', $1)`;

    const start = performance.now();
    const items = await this.prisma.$queryRawUnsafe<RawFtsRow[]>(
      sqlQuery,
      query,
      limit,
      offset,
    );
    const latencyMs = parseFloat((performance.now() - start).toFixed(2));

    // Get count for hits
    const countResult = await this.prisma.$queryRawUnsafe<CountRow[]>(
      `SELECT COUNT(*)::int as count FROM products WHERE search_vector @@ websearch_to_tsquery('english', $1)`,
      query,
    );
    const totalHits = countResult[0]?.count || 0;

    // Get explain plan
    let explainText = '';
    try {
      const explainResult = await this.prisma.$queryRawUnsafe<ExplainRow[]>(
        explainSql,
        query,
      );
      explainText = explainResult
        .map((row) => {
          const plan = row['QUERY PLAN'];
          if (typeof plan === 'string') return plan;
          const firstVal = Object.values(row)[0];
          return typeof firstVal === 'string'
            ? firstVal
            : JSON.stringify(firstVal ?? '');
        })
        .join('\n');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      explainText = `Failed to get explain plan: ${errorMessage}`;
    }

    // Get lexemes / tokens generated by websearch_to_tsquery
    let tokens: string[] = [];
    try {
      const tokensResult = await this.prisma.$queryRawUnsafe<TokensRow[]>(
        `SELECT websearch_to_tsquery('english', $1)::text as parsed_query`,
        query,
      );
      if (tokensResult[0]?.parsed_query) {
        tokens = [tokensResult[0].parsed_query];
      }
    } catch {
      // fallback
    }

    const formattedItems = items.map((item) => ({
      id: item.id,
      name: item.name,
      description: item.description,
      brand: item.brand,
      category: item.category,
      tags: item.tags || [],
      price: Number(item.price),
      rating: Number(item.rating),
      stock: Number(item.stock),
      score: Number(item.score),
      highlights: {
        name: item.highlighted_name ? [item.highlighted_name] : undefined,
        description: item.highlighted_desc
          ? [item.highlighted_desc]
          : undefined,
      },
    }));

    return {
      engine: 'fts',
      latencyMs,
      totalHits,
      items: formattedItems,
      queryInfo: {
        rawQuery: `SELECT id, name, description, brand, category, tags, price, rating, stock, "createdAt",
       ts_rank(search_vector, websearch_to_tsquery('english', '${query}')) as score,
       ts_headline('english', name, websearch_to_tsquery('english', '${query}'), 'StartSel="<b class=""search-highlight"">", StopSel=</b>, HighlightAll=TRUE') as highlighted_name
FROM products 
WHERE search_vector @@ websearch_to_tsquery('english', '${query}')
ORDER BY score DESC 
LIMIT ${limit} OFFSET ${offset};`,
        explainText,
        tokens,
      },
    };
  }
}
